<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32204" started-at="2019-05-22T17:59:04Z" finished-at="2019-05-22T17:59:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32204" started-at="2019-05-22T17:59:04Z" finished-at="2019-05-22T17:59:36Z">
      <class name="com.qa.testcases.LoginPageTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.LoginPageTests@6f7fd0e6]" name="setUp" is-config="true" duration-ms="30471" started-at="2019-05-22T17:59:04Z" finished-at="2019-05-22T17:59:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateLoginPageTitleTest()[pri:1, instance:com.qa.testcases.LoginPageTests@6f7fd0e6]" name="validateLoginPageTitleTest" duration-ms="129" started-at="2019-05-22T17:59:34Z" finished-at="2019-05-22T17:59:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title not Correct expected [ogin | Salesforce] but found [Login | Salesforce]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title not Correct expected [ogin | Salesforce] but found [Login | Salesforce]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.testcases.LoginPageTests.validateLoginPageTitleTest(LoginPageTests.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.LoginPageTests@6f7fd0e6]" name="tearDown" is-config="true" duration-ms="1531" started-at="2019-05-22T17:59:34Z" finished-at="2019-05-22T17:59:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.LoginPageTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
